name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
        version: 9.x
      - uses: actions/setup-nodev3
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm install --frozen-lockfile
      - run: npm run ci
